#!/bin/bash

if [ ! -d ".git" ]; then
    echo ".git does NOT exists"
    exit 1
fi

if [[ $(cat .git/config | grep url) != *"@"* ]]; then
    username=$(cat .git/config | grep url | cut -d '/' -f 4)
    repo=$(cat .git/config | grep url | cut -d '/' -f 5)
    git remote set-url origin git@github.com:$username/$repo
    echo "Success in changing from HTTP to SSH."

else
    echo "Already using SSH key."
fi

