#!/bin/bash


username=$1
repo_name=$2

# Check if username is empty
if [[ -z $username ]]; then
    echo "Username required."
    echo "Usage: git install Username RepoName"
    exit 1
fi

# Check if Repo name is empty
if [[ -z $repo_name ]]; then
    echo "Repo name required."
    echo "Usage: git install Username RepoName"
    exit 1
fi

git clone git@github.com:$username/$repo_name

