#!/bin/sh


repo_name=$1
second_arg=$2
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1
private_flag=', "private" : "true"'
test -z $second_arg && echo "making a public repo" &&  private_flag=''


curl -u 'saccharide' https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"$private_flag}" 
git init
git remote add origin git@github.com:saccharide/$repo_name.git
