#!/bin/sh

username=$1
repo_name=$2
private_arg=$3
test -z $username && echo "Username required." 1>&3 && exit 1
test -z $repo_name && echo "Repo name required." 1>&3 && exit 1
private_flag=', "private" : "true"'
test -z $private_arg && echo "Making a public repo ... ..." &&  private_flag=''
if [ ! $private_flag == '' ]; then
    echo "Making a private repo ... ..."
fi

curl -u $username https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"$private_flag}" 
git init
git remote add origin git@github.com:$username/$repo_name.git
