#!/bin/bash

if [ ! -d ".git" ]; then
    echo ".git does NOT exists"
    exit 1
fi

if [[ $(cat .git/config | grep url) != *"https://"* ]]; then
    username=$(cat .git/config | grep url | cut -d ':' -f 2 | cut -d '/' -f 1)
    repo=$(cat .git/config | grep url | cut -d ':' -f 2 | cut -d '/' -f 2)
    git remote set-url origin "https://github.com/$username/$repo" 
    echo "Success in changing from SSH to HTTP."
else
    echo "Already using HTTP URL."
fi

