#!/bin/bash

homebin="$HOME/bin"
if [ ! -d "$homebin" ]; then
    echo "Making $homebin"
    mkdir $homebin
fi

echo "Copying git-addons to $homebin ..."

cp git* $HOME/bin

echo "Finished!"
if [[ -z $(cat ~/.bashrc | grep "export PATH=\$HOME/bin:\$PATH") ]]; then
    echo "Adding \$HOME/bin to path ..."
    echo "export PATH=\$HOME/bin:\$PATH" >> ~/.bashrc
fi
